name: Gitleaks Code Scan
description: Run Gitleaks on Push and PR events
branding:
  color: orange
  icon: shield
inputs:
  config-path:
    description: 'Path to config (relative to $GITHUB_WORKSPACE)'
    required: false
    default: '.github/.gitleaks.toml'
outputs:
  result: # id of output
    description: 'Gitleaks log output'
  exitcode: # id of output
    description: 'Success for failure value from scan'
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.config-path }}